version: "3.8"

services:
  web:
    build: .
    ports:
    - "8081:3000"
    container_name: hello-docker-healthcheck
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3